### ISSUE TITLE
Error in asm code when building on macOS

### ISSUE THREAD

**Issue by jeffgca** [xnamahx/BolitasMutantes#1]
I tried building this on macOS ( 10.14.6 (18G3020) ) and got surprisingly far but got this error:

In file included from /Users/jeff/code/audio/BolitasMutantes/mi/marbles/random/distributions.h:36:
/Users/jeff/code/audio/BolitasMutantes/mi/stmlib/dsp/dsp.h:150:33: error: invalid output constraint '=w' in asm
    __asm ("vsqrt.f32 %0, %1" : "=w" (result) : "w" (x) );

Here's the code:

<pre>#ifdef TEST
  inline float Sqrt(float x) {
    return sqrtf(x);
  }
#else
  inline float Sqrt(float x) {
    float result;
    __asm ("vsqrt.f32 %0, %1" : "=w" (result) : "w" (x) );
    return result;
  }
#endif
</pre>

...it looks like I could set the variable TEST and the build would skip using the inline asm code? I've not debugged build scripts in a while, do you have any pointers on how to do this?

**Comment by jeffgca** [comment]
...just commenting out the 'else' branch of the code ( above ) results in a successful build.

**Comment by xnamahx** [comment]
Awesome @canuckistani , great to hear.
